import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Navbar from '@component/Navbar'
import TransitionContext from '@context/TransitionContext'
import { NavigationContextProvider } from '@context/NavigationContext'
import InitTransition from '@component/transition/InitTransition'
import Background from '@component/BackgroundPage'
import { getBackgroundImage } from '@service/webtoonInfo'
import QueryClientContext from '@context/QueryClientContext'
import AuthContext from '@/context/AuthContext'
import NextTopLoader from 'nextjs-toploader';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const backgroundImage = await getBackgroundImage();

  return (
    <html lang="en">
        <body className={` pt-[80px]`}>
          {/* <InitTransition/> */}
          {/* <Background backgroundImage={backgroundImage}></Background> */}
          <AuthContext>
            <QueryClientContext>
              <NavigationContextProvider>
                  <NextTopLoader />
                  <Navbar></Navbar>
                  <div className = 'relative w-[100dvw] h-[100dvh]'>
                        <main>
                            {children}                     
                        </main>
                  </div>
                  <div id = "modal"></div>
              </NavigationContextProvider>
            </QueryClientContext>
          </AuthContext>
        </body>
    </html>
  )
}
