import type { Metadata } from 'next'
import '@/app/globals.css'
import Navbar from '@component/Navbar'
import { NavigationContextProvider } from '@context/NavigationContext'
import { getBackgroundImage } from '@service/webtoonInfo'
import QueryClientContext from '@context/QueryClientContext'
import AuthContext from '@/context/AuthContext'
import NextTopLoader from 'nextjs-toploader';
import Footer from '@/components/Footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
        <body className={`pt-[80px]`}>
          <AuthContext>
            <QueryClientContext>
              <NavigationContextProvider>
                  <NextTopLoader />
                  <Navbar></Navbar>
                  <div className = 'relative w-[100dvw] h-[100dvh]'>
                        <main>
                            {children}
                            <Footer />                     
                        </main>
                  </div>
                  <div id = "modal"></div>
              </NavigationContextProvider>
            </QueryClientContext>
          </AuthContext>
        </body>
    </html>
  )
}
