import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/app/globals.css'
import Navbar from '@component/Navbar'
import {useRouter} from 'next/navigation'
import TransitionContext from '@context/TransitionContext'
import { NavigationContextProvider } from '@context/NavigationContext'
import InitTransition from '@component/transition/InitTransition'
import Background from '@component/BackgroundPage'
import { getBackgroundImage } from '@service/webtoonInfo'
import LoginContextProvider from '@context/LoginContextProvider'
import QueryClientContext from '@context/QueryClientContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const backgroundImage = await getBackgroundImage();

  return (
    <html lang="en">
        <body className={inter.className}>
          {/* <InitTransition/> */}
          {/* <Background backgroundImage={backgroundImage}></Background> */}
          <QueryClientContext>
          <NavigationContextProvider>
            <LoginContextProvider>
              <Navbar></Navbar>
              <div className = 'relative'>
                    <main>
                        {children}                     
                    </main>
              </div>
              <div id = "modal"></div>

              </LoginContextProvider>
          </NavigationContextProvider>
          </QueryClientContext>
        </body>
    </html>
  )
}
